version: '3'
services:
  qbh:
    build: .
    image: qbh:latest
    ports:
    - "8888:8888"
    volumes:
    - .:/app
    - ./vamp:/root/vamp
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root
